name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Unit Test
      run: swift xcodebuild -project JenkinsDemo/JenkinsDemo.xcodeproj -scheme JenkinsDemo -sdk iphonesimulator13.0 clean test
