name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Unit Test
      run: xcodebuild -project JenkinsDemo.xcodeproj -scheme JenkinsDemo clean test
