on: [push]
name: JenkinsDemo
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8 Plus']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Unit Test
        run: |
          xcodebuild -project JenkinsDemo.xcodeproj -scheme JenkinsDemo -destination "${destination}" CODE_SIGN_IDENTITY="" clean test
        env: 
         destination: ${{ matrix.destination }}
